[[services]]
name = "9ball"
path = "service/9ball"
build_cmd = "cargo build --target riscv64gc-unknown-none-elf && mkdir -p build && cp ../../target/riscv64gc-unknown-none-elf/debug/nineball build/9ball.bin"
output_bin = "build/9ball.bin"
kind = "root_task"
