[[services]]
name = "9ball"
path = "service/9ball"
build_cmd_release = "bash build.sh --release"
build_cmd_debug = "bash build.sh"
output_bin = "build/9ball.bin"
kind = "root_task"
[[services]]
name = "factotum"
path = "service/factotum"
build_cmd_release = "bash build.sh --release"
build_cmd_debug = "bash build.sh"
output_bin = "build/factotum.bin"
kind = "server"
[[services]]
name = "unicorn"
path = "service/unicorn"
build_cmd_release = "bash build.sh --release"
build_cmd_debug = "bash build.sh"
output_bin = "build/unicorn.bin"
kind = "server"
[[services]]
name = "ns16550a"
path = "drivers/ns16550a"
build_cmd_release = "bash build.sh --release"
build_cmd_debug = "bash build.sh"
output_bin = "build/ns16550a.bin"
kind = "driver"
[[services]]
name = "virtio-blk"
path = "drivers/virtio/block"
build_cmd_release = "bash build.sh --release"
build_cmd_debug = "bash build.sh"
output_bin = "build/virtio-blk.bin"
kind = "driver"
[[services]]
name = "manifest"
path = "config"
output_bin = "manifest.toml"
kind = "file"
