[[services]]
name = "9ball"
path = "service/9ball"
build_cmd_release = "bash build.sh --release"
build_cmd_debug = "bash build.sh"
output = "build/9ball.elf"
kind = "root_task"
[[services]]
name = "factotum"
path = "service/factotum"
build_cmd_release = "bash build.sh --release"
build_cmd_debug = "bash build.sh"
output = "build/factotum.elf"
kind = "server"
[[services]]
name = "unicorn"
path = "service/unicorn"
build_cmd_release = "bash build.sh --release"
build_cmd_debug = "bash build.sh"
output = "build/unicorn.elf"
kind = "server"
[[services]]
name = "ns16550a"
path = "drivers/ns16550a"
build_cmd_release = "bash build.sh --release"
build_cmd_debug = "bash build.sh"
output = "build/ns16550a.elf"
kind = "driver"
[[services]]
name = "virtio-blk"
path = "drivers/virtio/block"
build_cmd_release = "bash build.sh --release"
build_cmd_debug = "bash build.sh"
output = "build/virtio-blk.elf"
kind = "driver"
[[services]]
name = "manifest"
path = "config"
output = "manifest.toml"
kind = "file"
[[libraries]]
name = "libglenda-rs"
path = "lib/libglenda-rs"
build_cmd_release = "bash build.sh --release"
build_cmd_debug = "bash build.sh"
[features]
kernel = []
