[[services]]
name = "9ball"
path = "service/9ball"
build_cmd = "bash build.sh"
output_bin = "build/9ball.bin"
kind = "root_task"
[[services]]
name = "factotum"
path = "service/factotum"
build_cmd = "bash build.sh"
output_bin = "build/factotum.bin"
kind = "server"

[[services]]
name = "unicorn"
path = "service/unicorn"
build_cmd = "bash build.sh"
output_bin = "build/unicorn.bin"
kind = "server"
