[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
which = "6.0"
anyhow = "1.0"
tempfile = "3.10"
serde = { version = "1.0", features = ["derive"] }
toml = "0.7"
