[package]
name = "drivers"
version = "0.1.0"
edition = "2024"
description = "Kernel drivers for Glenda"

[lib]
name = "drivers"
path = "src/driver.rs"
crate-type = ["rlib"]

[dependencies]
fdt = "0.1.5"
spin = "0.9"

[features]
uart-unicode = []